config/routes.rb
MusicInventory::Application.routes.draw do
  resources :bands
  resources :albums
  resources :tracks
  resource :sessions, :only => [:new, :create, :destroy]
  resource :users, :only => [:new, :create]
end

app/models/album.rb
class Album < ActiveRecord::Base
  attr_accessible :band_id, :live, :name
  validates :name, :presence => :true, :uniqueness => :true
  validates :band_id, :presence => :true



  belongs_to :band
  has_many :tracks, :dependent => :destroy


end

app/models/band.rb
class Band < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => :true, :uniqueness => :true

  has_many :albums, :dependent => :destroy
  has_many :tracks, :through => :albums

end

app/models/track.rb
class Track < ActiveRecord::Base
  attr_accessible :album_id, :bonus, :lyrics, :name
  validates :album_id, :name, :presence => :true
  validates :name, :uniqueness => {:scope => :album_id}

  belongs_to :album
  has_one :band, :through => :album
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :session_token
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @bands = Band.all
    @album = Album.new
    render :new
  end

  def create
    @album = Album.new(params[:album])
    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors]  = @album.errors.full_messages
      @bands = Band.all
      render :new
    end
  end

  def index
    @albums = Album.all
    render :index
  end

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    @album.update_attributes(params[:album])

    if @album.save
      render :show
    else
      flash[:errors]  = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    flash[:confirmation] = "#{@album.name} deleted!"
    redirect_to albums_url
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def login_user(user)
    user.session_token = SecureRandom.urlsafe_base64
    user.save!

    session[:session_token] = user.session_token
    redirect_to bands_url
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def authenticate!
    p session
    if !logged_in?
      redirect_to new_sessions_url
    end
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_filter :authenticate!

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(params[:band])

    if @band.save
      redirect_to band_url(@band)
    else
      flash[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def index
    @bands = Band.all
    render :index
  end

  def update
    @band = Band.find(params[:id])
    @band.update_attributes(params[:band])
    if @band.save
      render :show
    else
      flash[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    flash[:confirmation] = "#{@band.name} deleted!"
    redirect_to bands_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    @user = User.find_by_email_and_password(params[:user][:email], params[:user][:password])
    if @user
     login_user(@user)
    else
      render :new
    end
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_filter :authenticate!

  def new
    @albums = Album.all
    @track = Track.new
    render :new
  end

  def create
    p params
    @track = Track.new(params[:track])
    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      @albums = Album.all
      render :new
    end
  end

  def index
    @tracks = Track.all
    render :index
  end

  def show
    @track = Track.find(params[:id])
    render :show
  end

  def edit
    @track = Track.find(params[:id])
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    @track.update_attributes(params[:track])

    if @track.save
      render :show
    else
      flash[:errors]  = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    flash[:confirmation] = "#{@track.name} deleted!"
    redirect_to tracks_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      login_user(@user)
    else
      render :new
    end

  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album_form.html.erb
<% saved = !! album.id %>

<form action="<%= saved ? album_url(album) : albums_url %>" method="post">
	<%= render :partial => "shared/is_put_request" if saved %>

	<% if !saved %>
		<label for="album_band">Choose band for album</label>
		<select name="album[band_id]" id="album_band">
			<% bands.each do |band| %>
				<option value="<%= band.id %>" <%="selected" if band.id == album.band_id%>>
					<%= band %>
				</option>
			<% end %>
		</select>
	<% else %>
		Band: <%=album.band.name%>
	<% end %>
	<br>

	<label for="album_name">Name</label>
	<input type="text" name="album[name]" id="album_name"
					value="<%= album.name %>">
	<label for="album_live">Live album?</label>
	<input type="checkbox" name="album[live]"
				 value="true" id="album_live" <%= "checked" if album.live %>>

	<input type="submit" value="<%= saved ? "Update Album" : "Create Album" %>">
</form>

app/views/albums/_albums_list.html.erb
<ul>
	<% albums.each do |album|%>
		<li><%= link_to album.name, album_url(album) %>
			<%if include_tracks%>
				<%= render :partial => "tracks/track_list", :locals => {:tracks => album.tracks} %>
			<%end%>
			</li>
	<%end%>
</ul>

app/views/albums/edit.html.erb
<%= render :partial => "shared/show_errors" %>

<h1>Change the name of the album <%= @album %></h1>
<%= render :partial => "albums/album_form", :locals => {:album => @album} %>
<form action="<%=album_url(@album)%>" method="post">
	<input type="hidden" name="_method" value="delete">
	<input type="submit" value="Delete <%=@album.name%>">
</form>

app/views/albums/index.html.erb
<%= flash[:confirmation] if flash[:confirmation]%>
<h1>Albums!</h1>
<%= render :partial => "albums/albums_list", :locals => {:albums => @albums, :include_tracks => false} %>

app/views/albums/new.html.erb
<%= render :partial => "shared/show_errors"%>
<h1>Create an album!</h1>
<%= render :partial => "albums/album_form", :locals => {:bands => @bands, :album => @album}  %>

app/views/albums/show.html.erb
<h1><%= @album.name %></h1>
<ul>
	<li><%= link_to @album.band.name, band_url(@album.band) %></li>
	<li>Type: <%= @album.live ? "Live" : "Studio"%></li>
	<li>Tracks <%= render :partial => "tracks/track_list",
												:locals => {:tracks => @album.tracks}%></li>
</ul>

app/views/bands/_band_form.html.erb
<% saved = !!band.id %>

<form action="<%= saved ? band_url(band) : bands_url %>" method="post">
	<%= render :partial => "shared/is_put_request" if saved %>

	<label for="band_name">Name</label>
	<input type="text" name="band[name]" id="band_name"
					value="<%= band.name %>">

	<input type="submit" value="<%= saved ? "Update Band" : "Create Band" %>">
</form>

app/views/bands/edit.html.erb
<%= render :partial => "shared/show_errors" %>

<h1>Change the name of <%= @band %></h1>
<%= render :partial => "bands/band_form", :locals => {:band => @band} %>
<form action="<%=band_url(@band)%>" method="post">
	<input type="hidden" name="_method" value="delete">
	<input type="submit" value="Delete <%=@band.name%>">
</form>

app/views/bands/index.html.erb
<%= flash[:confirmation] if flash[:confirmation]%>

<h1> All Bands </h1>
<ul>
	<% @bands.each do |band|  %>
		<li><%= link_to band.name, band_url(band) %> </li>
	<%end%>
</ul>

app/views/bands/new.html.erb
<%= render :partial => "shared/show_errors" %>

<h1> Create a band!</h1>
<%= render :partial => "bands/band_form", :locals => {:band => @band} %>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h2>Albums!</h2>
<%= render :partial => "albums/albums_list", :locals => {:albums => @band.albums, :include_tracks => true}%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicInventory</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_is_put_request.html.erb
<input type="hidden" name="_method" value="put">

app/views/shared/_show_errors.html.erb
<%= flash[:errors].join(", ") unless flash[:errors].nil? %>

app/views/tracks/_track_form.html.erb
<% saved = !! track.id %>

<form action="<%= saved ? track_url(track) : tracks_url %>" method="post">
	<%= render :partial => "shared/is_put_request" if saved %>
	<% if !saved %>
		<label for="track_album">Choose album for track</label>
		<select name="track[album_id]" id="track_album">
			<% albums.each do |album| %>
				<option value="<%= album.id %>" <%="selected" if
					album.id == track.album_id%>><%= album %> </option>
			<% end %>
		</select>
	<% else %>
		Album: <%=track.album.name%>
	<% end %>
	<br>

	<label for="track_name">Name</label>
	<input type="text" name="track[name]" id="track_name"
					value="<%= track.name %>">
					<br>
	<label for="track_bonus">Bonus track?</label>
	<input type="checkbox" name="track[bonus]"
				 value="true" id="album_bonus" <%= "checked" if track.bonus %>>
				 <br>
	<label for="track_lyrics">Lyrics:</label>
	<textarea name="track[lyrics]" id="track_lyrics"></textarea>
	<br>
	<input type="submit" value="<%= saved ? "Update Track" : "Create Track" %>">

	<input type="hidden"
	         name="authenticity_token"
	         value="<%= form_authenticity_token %>">
</form>

app/views/tracks/_track_list.html.erb
<ul>
	<% tracks.each do |track|%>
		<li><%= link_to track.name, track_url(track) %></li>
	<%end%>
</ul>

app/views/tracks/edit.html.erb
<%= render :partial => "shared/show_errors" %>

<h1>Change the name of the track <%= @track.name %></h1>
<%= render :partial => "tracks/track_form", :locals => {:track => @track} %>
<form action="<%=track_url(@track)%>" method="post">
	<input type="hidden" name="_method" value="delete">
	<input type="submit" value="Delete <%=@track.name%>">
</form>

app/views/tracks/index.html.erb
<%= flash[:confirmation] if flash[:confirmation]%>
<h1>Tracks</h1>
<%= render :partial => "tracks/track_list", :locals => {:tracks => @tracks} %>

app/views/tracks/new.html.erb
<%= render :partial => "shared/show_errors"%>
<h1>Create an Track!</h1>
<%= render :partial => "tracks/track_form", :locals => {:albums => @albums, :track => @track}  %>

app/views/tracks/show.html.erb
<h1><%= @track.name %></h1>
	<ul>
		<li>Album: <%= link_to @track.album.name, album_url(@track.album) %></li>
		<li>Band: <%=link_to @track.band.name, band_url(@track.band) %></li>
	</ul>
	<h2> Lyrics:</h2>

	<p> <%= @track.lyrics %> </p>

app/views/users/new.html.erb
<h1>Create Account</h1>

<form action= "<%=users_url%>" method="post">
	<label for "email">Email Address</label>
	<input type="text" name="user[email]" id="email">
	<br>
	<label for "password">Password</label>
	<input type="password" name="user[password]" id="password">
	<input type="submit">

	<input type="hidden"
	         name="authenticity_token"
	         value="<%= form_authenticity_token %>">
</form>